### ISSUE TITLE
Automatic updating of battery charge data does not work

### ISSUE THREAD

**Issue by ipwin-github** [SARDONYX-sard/bluetooth-battery-monitor#13]
The automatic update of battery charge data does not work. You can update the data only by clicking "Reload" in the tray. Because of this, the "Update interval" and "Warn battery" settings do not work either.

**Comment by SARDONYX-sard** [comment]
I released 0.3.1.

https://github.com/SARDONYX-sard/bluetooth-battery-monitor/releases/tag/0.3.1

It should work as far as I have tested.

**Comment by ipwin-github** [comment]
Yes, everything works in the updated release. Thanks!

**Comment by SARDONYX-sard** [comment]
Glad it seems to be working well!
