### ISSUE TITLE
Autorun of the program does not work

### ISSUE THREAD

**Issue by ipwin-github** [SARDONYX-sard/bluetooth-battery-monitor#14]
Autorun does not work. And the autorun setting itself is constantly being reset. For example, if you go to the "Settings" menu and then return to the Home menu, the "Autostart" setting is reset. In the previous version 2.0.2, autorun works.

**Comment by SARDONYX-sard** [comment]
Oops, the rewritten version (0.3.0) still needs to be improved. (Actually, the rewritten version has not been tested much.)

Thanks for taking the trouble to try it. I'll try to fix it a bit. Please wait.

**Comment by ipwin-github** [comment]
There are no more problems with autorun in the updated version. Autorun is working.

**Comment by SARDONYX-sard** [comment]
It's wonderful. Now I'll close.
